apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-app
  labels:
    app: quiz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-app
  template:
    metadata:
      labels:
        app: quiz-app
    spec:
      containers:
      - name: quiz-app
        image: ftutorials/quiz:scm
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-service
  labels:
    app: quiz-app
spec:
  selector:
    app: quiz-app
  ports:
  - name: http
    protocol: TCP
    port: 80        # Port exposé à l'extérieur du cluster
    targetPort: 3000    # Port sur lequel le conteneur écoute
  type: LoadBalancer    
